name: APP CUARTO DATOS Pipeline

on:
  push:
    branches: [ main ]

jobs:

  build-and-push-image:
    runs-on: [self-hosted]
    if: github.ref == 'refs/heads/main'
    steps:

    - name: Construir imagen docker 
      run: |
        cd /docker-images
        cp Dockerfile /docker-images/Dockerfile
        echo "Construyendo imagen en VISERTION..."
        docker build -t cuarto-datos:latest .
        echo "Listando imagenes..."
        docker images
  
  apply-docker:
    runs-on: [self-hosted]
    if: github.ref == 'refs/heads/main' 
    steps:
    
    - name: Deploy to docker
      run: |
        echo "Desplegando aplicación CUATO DATOS en VISERTION..."
        docker-compose down
        echo "Aplicando manifiesto..."
        docker-compose up -d 
        echo "Limpiando recursos docker..."
        docker system prune -f
        echo "Despliegue finalizado con exito"

        
    



  
