name: APP CUARTO DATOS Pipeline

on:
  push:
    branches: [ main ]

jobs:

  build-and-push-image:
    runs-on: [self-hosted]
    if: github.ref == 'refs/heads/main'
    steps:

    - name: Construir imagen docker 
      run: |
        echo "Copiando dockerfile en VISERTION..."
        mkdir /dockerfile && cd /dockerfile
        curl -o Dockerfile -L https://github.com/oderroot/cuarto-datos-front/blob/main/Dockerfile
        echo "Construyendo imagen en VISERTION..."
        docker build -t ${{ secrets.IMAGE_NAME }}: latest
        echo "Listando imagenes..."
        docker images
  
  apply-docker:
    runs-on: [self-hosted]
    if: github.ref == 'refs/heads/main' 
    steps:
    
    - name: Deploy to docker
      run: |
        echo "Desplegando aplicación CUATO DATOS en VISERTION..."
        docker-compose down ${{ secrets.REPO }}
        echo "Aplicando manifiesto..."
        docker-compose up -d ${{ secrets.REPO }}
        echo "Limpiando recursos dcoker..."
        docker system prune -f
        echo "Despliegue finalizado con exito"

        
    



  
